//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillsListASPNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Body { get; set; }
        public string Category { get; set; }
        public string Owner { get; set; }
        public System.DateTime PostDate { get; set; }
        public string Location { get; set; }
        public string Image { get; set; }
    }
}
